export enum SkillLevel {
  BOSKI = 0,
  UTOPIJNY = 1,
  MAGICZNY = 2,
  MITYCZNY = 3,
  NIEZIEMSKI = 4,
  TYTANICZNY = 5,
  NADPRZYRODZONY = 6,
  SWIATOWEJ_KLASY = 7,
  MISTRZOWSKI = 8,
  BLYSKOTLIWY = 9,
  OLSNIEWAJACY = 10,
  FANTASTYCZNY = 11,
  ZNAKOMITY = 12,
  SOLIDNY = 13,
  ZADOWALAJACY = 14,
  PRZECIETNY = 15,
  SLABY = 16,
  KIEPSKI = 17,
  NEDZNY = 18,
  FATALNY = 19,
  BEZNADZIEJNY = 20
}

export enum FormLevel {
  ZNAKOMITY = 0,
  SOLIDNY = 1,
  ZADOWALAJACY = 2,
  PRZECIETNY = 3,
  SLABY = 4,
  KIEPSKI = 5,
  NEDZNY = 6,
  FATALNY = 7,
  BEZNADZIEJNY = 8
}

export enum LeaderLevel {
  SOLIDNY = 0,
  ZADOWALAJACY = 1,
  PRZECIETNY = 2,
  SLABY = 3,
  KIEPSKI = 4,
  NEDZNY = 5,
  FATALNY = 6,
  BEZNADZIEJNY = 7
}

export enum FormationExperienceLevel {
  OLSNIEWAJACY = 0,
  FANTASTYCZNY = 1,
  ZNAKOMITY = 2,
  SOLIDNY = 3,
  ZADOWALAJACY = 4,
  PRZECIETNY = 5,
  SLABY = 6,
  KIEPSKI = 7
}

export enum SponsorLevel {
  PRZYSYLAJA_POEMATY_MILoSNE = 0,
  W_SIODYM_NIEBIE = 1,
  SZALEJA_Z_RADOŚCI = 2,
  ZACHWYCENI = 3,
  ZADOWOLENI = 4,
  SPOKOJNI = 5,
  OBOJĘTNI = 6,
  ZIRYTOWANI = 7,
  WŚCIEKLI = 8,
  ŻADNI_KRWI = 9
}

export enum FanMoodLevel {
  PRZYSYLAJA_POEMATY_MILoSNE = 0,
  W_SIODYM_NIEBIE = 1,
  SZALEJA_Z_RADOŚCI = 2,
  ZACHWYCENI = 3,
  ZADOWOLENI = 4,
  SPOKOJNI = 5,
  OBOJĘTNI = 6,
  ZAWIEDZENI = 7,
  ZIRYTOWANI = 8,
  ROZZŁOŚCENI = 9,
  WŚCIEKLI = 10,
  ŻADNI_KRWI = 11
}

export enum MatchExpectationLevel {
  PONIŻMY_ICH = 0,
  BULKA_Z_MASLEM = 1,
  WYGRAMY = 2,
  JESTEŚMY_FAWORYTAMI = 3,
  MAMY_PRZEWAGE = 4,
  SZANSE_SĄ_WYRÓWNANE = 5,
  TO_ONI_MAJA_PRZEWAGE = 6,
  TO_ONI_SĄ_FAWORYTAMI = 7,
  PRZEGRAMY = 8,
  NIE_MAMY_SZANS = 9,
  LEPIEJ_SIE_NIE_POKAZUJMY = 10
}

export enum SeasonExpectationLevel {
  WYPREDSZAMY_TĘ_LIGE_O_LATA_ŚWIETLNE = 0,
  MISTRZOSTWO_MUSI_BYC_NASZE = 1,
  WALCZYMY_O_TYTUL = 2,
  NASZE_MIEJSCE_TO_CZOŁOWA_CZWÓRKA = 3,
  SRODEK_TABELI_POWINIEN_BYC_NASZ = 4,
  BEDZIEMY_MUSIELI_WALCZYC_O_UTRZYMANIE = 5,
  KAŻDY_DZIEŃ_W_TEJ_LIDZE_TO_CUD = 6,
  TA_LIGA_CAŁKOWICIE_NAS_PRZERASTA = 7
}

export enum PersonalityLevel {
  UWIELBIANY_PRZEZ_ZESPÓL = 0,
  POPULARNY = 1,
  SYMPATYCZNY = 2,
  PRZYJEMNY = 3,
  KONTROWERSYJNY = 4,
  ZŁOŚLIWY = 5
}

export enum HonestyLevel {
  ŚWIATOBLIWY = 0,
  SZLACHETNY = 1,
  PRAWY = 2,
  UCZCIWY = 3,
  NIEUCZCIWY = 4,
  PODŁY = 5
}

export enum AggressivenessLevel {
  NIEZRÓWNOWAŻONY = 0,
  PORYWCZY = 1,
  Z_CHARAKTEREM = 2,
  ZRÓWNOWAŻONY = 3,
  OPANOWANY = 4,
  SPOKOJNY = 5
}

export enum TeamMoraleLevel {
  RAJ_NA_ZIEMI = 0,
  W_SIODYM_NIEBIE = 1,
  ZACHWYCENI = 2,
  ZADOWOLENI = 3,
  SPOKOJNI = 4,
  OBOJĘTNI = 5,
  OPANOWANI = 6,
  ZIRYTOWANI = 7,
  WŚCIEKLI = 8,
  ŻADNI_KRWI = 9,
  JAK_W_CZASIE_ZIMNEJ_WOJNY = 10
}

export enum TeamConfidenceLevel {
  NIEMOŻLIWIE_PRZESADZONA = 0,
  PRZESADZONA = 1,
  LEKKO_PRZESADZONA = 2,
  CUDOWNA = 3,
  MOCNA = 4,
  PRZYZWOITA = 5,
  KIEPSKA = 6,
  NĘDNA = 7,
  FATALNA = 8,
  BEZNADZIEJNA = 9
}
